on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  version-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version patch
        uses: ./
